# Workflow
name: upload-artifact-sample

on:
  # 発動条件 push
  push:
    # 発動ブランチ test/*
    branches:
      - test/*

# JOB
jobs:
  artifact-sample:
    runs-on: ubuntu-latest
    steps:
      # 成果用としてアップロードするファイルを作成
      - name: artifact output
        id: rnd
        run: |
          echo "Hello, World" > hello.txt
      # 成果物アップロード
      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          name: hello
          path: hello.txt
          retention-days: 3
